# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target ‘瀑布流’ do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 瀑布流
  pod 'SDWebImage', '~> 4.0.0'

end
