# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'MVVMTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MVVMTest
  pod 'ReactiveObjC', '~> 3.0.0'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'MJExtension', '~> 3.0.13'
  pod 'SDWebImage', '~> 4.0.0'
end
