# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target '自定义流水布局' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 自定义流水布局
  pod 'SDWebImage', '~> 4.0.0'

end
