platform :ios, '9.0'

target 'ReactiveCocoa' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactiveCocoa
  pod 'ReactiveObjC', '~> 3.0.0'

end

target 'MVVM+ReactiveCocoa' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for ReactiveCocoa
    pod 'ReactiveObjC', '~> 3.0.0'
    
end
